<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\ObjRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity from profile
 * @profile ca.profile.json
 */
#[Entity(repositoryClass: ObjRepository::class)]
#[MeiliIndex(
	primaryKey: 'id',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Obj
{
	public const FILTERABLE_FIELDS = [
		'table',
		'access',
		'status',
		'primaryDateSet',
		'sourceSet',
		'caObjectRepresentationsMediaSmallUrl',
		'caObjectRepresentationsMediaMediumUrl',
		'caObjectRepresentationsMediaOriginalUrl',
		'georeference',
		'caPlacesPreferredLabelsName',
		'caCollectionsPreferredLabelsName',
		'RHSKeywordsList',
		'lcshTerms',
		'caEntitiesPreferredLabelsDisplayname',
		'objectDate',
		'internalNotes',
		'externalLink',
		'dimensions',
		'rightsSet',
	];

	public const SORTABLE_FIELDS = ['id'];
	public const SEARCHABLE_FIELDS = ['preferredLabelsName', 'description'];

	/**
	 * Profile field "id"
	 * @types int (storageHint=int)
	 * @stats total=2744, nulls=0, distinct=2744
	 */
	#[Column(type: Types::INTEGER, nullable: false)]
	#[Id]
	public ?int $id = null;

	/**
	 * Profile field "idno"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=2740
	 */
	#[Column(length: 11, nullable: true)]
	public ?string $idno = null;

	/**
	 * Profile field "table"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=1
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $table = null;

	/**
	 * Profile field "preferred_labels.name"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=2682
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(length: 157, nullable: true)]
	public ?string $preferredLabelsName = null;

	/**
	 * Profile field "type_id"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=62
	 */
	#[Column(length: 24, nullable: true)]
	public ?string $typeId = null;

	/**
	 * Profile field "access"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=2
	 */
	#[Column(length: 13, nullable: true)]
	public ?string $access = null;

	/**
	 * Profile field "status"
	 * @types string (storageHint=string)
	 * @stats total=2744, nulls=0, distinct=2
	 */
	#[Column(length: 19, nullable: true)]
	public ?string $status = null;

	/**
	 * Profile field "primaryDateSet"
	 * @types string, array (storageHint=json)
	 * @stats total=2742, nulls=0, distinct=2
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $primaryDateSet = null;

	/**
	 * Profile field "sourceSet"
	 * @types string, array (storageHint=json)
	 * @stats total=2742, nulls=0, distinct=10
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $sourceSet = null;

	/**
	 * Profile field "ca_object_representations.media.small.url"
	 * @types string, array (storageHint=json)
	 * @stats total=2722, nulls=0, distinct=2721
	 * @urlLike true
	 * @imageLike true
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caObjectRepresentationsMediaSmallUrl = null;

	/**
	 * Profile field "ca_object_representations.media.medium.url"
	 * @types string, array (storageHint=json)
	 * @stats total=2722, nulls=0, distinct=2721
	 * @urlLike true
	 * @imageLike true
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caObjectRepresentationsMediaMediumUrl = null;

	/**
	 * Profile field "ca_object_representations.media.original.url"
	 * @types string, array (storageHint=json)
	 * @stats total=2722, nulls=0, distinct=327
	 * @imageLike true
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caObjectRepresentationsMediaOriginalUrl = null;

	/**
	 * Profile field "georeference"
	 * @types string, array (storageHint=json)
	 * @stats total=923, nulls=0, distinct=502
	 * @jsonLike true
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $georeference = null;

	/**
	 * Profile field "ca_places.preferred_labels.name"
	 * @types string, array (storageHint=json)
	 * @stats total=465, nulls=0, distinct=30
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caPlacesPreferredLabelsName = null;

	/**
	 * Profile field "ca_collections.preferred_labels.name"
	 * @types string, array (storageHint=json)
	 * @stats total=2319, nulls=0, distinct=1835
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caCollectionsPreferredLabelsName = null;

	/**
	 * Profile field "RHS_keywords_list"
	 * @types string, array (storageHint=json)
	 * @stats total=739, nulls=0, distinct=83
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $RHSKeywordsList = null;

	/**
	 * Profile field "lcsh_terms"
	 * @types string, array (storageHint=json)
	 * @stats total=448, nulls=0, distinct=176
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $lcshTerms = null;

	/**
	 * Profile field "ca_entities.preferred_labels.displayname"
	 * @types string, array (storageHint=json)
	 * @stats total=143, nulls=0, distinct=53
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $caEntitiesPreferredLabelsDisplayname = null;

	/**
	 * Profile field "description"
	 * @types string (storageHint=string)
	 * @stats total=2565, nulls=0, distinct=2512
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $description = null;

	/**
	 * Profile field "object_date"
	 * @types string, int, array (storageHint=json)
	 * @stats total=2643, nulls=0, distinct=1674
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $objectDate = null;

	/**
	 * Profile field "internal_notes"
	 * @types string, array (storageHint=json)
	 * @stats total=10, nulls=0, distinct=10
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $internalNotes = null;

	/**
	 * Profile field "external_link"
	 * @types string (storageHint=string)
	 * @stats total=3, nulls=0, distinct=3
	 * @naturalLanguageLike true
	 */
	#[Column(length: 31, nullable: true)]
	public ?string $externalLink = null;

	/**
	 * Profile field "dimensions"
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 */
	#[Column(length: 7, nullable: true)]
	public ?string $dimensions = null;

	/**
	 * Profile field "rightsSet"
	 * @types string (storageHint=string)
	 * @stats total=1, nulls=0, distinct=1
	 */
	#[Column(length: 2, nullable: true)]
	public ?string $rightsSet = null;
}
