<?php

namespace App\Controller\Admin;

use App\Entity\Obj;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Survos\EzBundle\Controller\AbstractEzCrudController;
use Survos\EzBundle\Field\LinkedTextField;

/**
 * Generated by code:meili:admin
 */
final class ObjCrudController extends AbstractEzCrudController
{
    /** TODO: adjust SHOW_ROUTE to your app show route */
    public const SHOW_ROUTE = 'admin_app_obj_show';

    public static function getEntityFqcn(): string
    {
        return \App\Entity\Obj::class;
    }

    protected function preferredFields(string $pageName): iterable
    {
        yield ArrayField::new('caObjectRepresentationsMediaSmallUrl');
        if ($pageName !== Crud::PAGE_INDEX) {
            return [];
        }

        return [];

        yield LinkedTextField::new('id', 'Id')
            ->setRoute(self::SHOW_ROUTE, 'id', 'id');
    }
}
