<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112143311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE obj (id INT NOT NULL, idno VARCHAR(11) DEFAULT NULL, table_field VARCHAR(10) DEFAULT NULL, preferred_labels_name VARCHAR(157) DEFAULT NULL, type_id VARCHAR(24) DEFAULT NULL, access VARCHAR(13) DEFAULT NULL, status VARCHAR(19) DEFAULT NULL, primary_date_set JSON DEFAULT NULL, source_set JSON DEFAULT NULL, ca_object_representations_media_small_url JSON DEFAULT NULL, ca_object_representations_media_medium_url JSON DEFAULT NULL, ca_object_representations_media_original_url JSON DEFAULT NULL, georeference JSON DEFAULT NULL, ca_places_preferred_labels_name JSON DEFAULT NULL, ca_collections_preferred_labels_name JSON DEFAULT NULL, rhskeywords_list JSON DEFAULT NULL, lcsh_terms JSON DEFAULT NULL, ca_entities_preferred_labels_displayname JSON DEFAULT NULL, description TEXT DEFAULT NULL, object_date JSON DEFAULT NULL, internal_notes JSON DEFAULT NULL, external_link VARCHAR(31) DEFAULT NULL, dimensions VARCHAR(7) DEFAULT NULL, rights_set VARCHAR(2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE obj');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
